/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { WaitingListEntry } from "./api";
export namespace Components {
    interface MsevcikAmbulanceWlApp {
        "ambulance": string;
        "apiUri": string;
        "basePath": string;
    }
    interface MsevcikAmbulanceWlEditor {
        "ambulance": string;
        "apiUri": string;
        "entryId": string;
    }
    interface MsevcikAmbulanceWlList {
        "ambulance": string;
        "apiUri": string;
        "selectedEntryId": string;
    }
}
export interface MsevcikAmbulanceWlEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMsevcikAmbulanceWlEditorElement;
}
export interface MsevcikAmbulanceWlListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMsevcikAmbulanceWlListElement;
}
declare global {
    interface HTMLMsevcikAmbulanceWlAppElement extends Components.MsevcikAmbulanceWlApp, HTMLStencilElement {
    }
    var HTMLMsevcikAmbulanceWlAppElement: {
        prototype: HTMLMsevcikAmbulanceWlAppElement;
        new (): HTMLMsevcikAmbulanceWlAppElement;
    };
    interface HTMLMsevcikAmbulanceWlEditorElement extends Components.MsevcikAmbulanceWlEditor, HTMLStencilElement {
    }
    var HTMLMsevcikAmbulanceWlEditorElement: {
        prototype: HTMLMsevcikAmbulanceWlEditorElement;
        new (): HTMLMsevcikAmbulanceWlEditorElement;
    };
    interface HTMLMsevcikAmbulanceWlListElement extends Components.MsevcikAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLMsevcikAmbulanceWlListElement: {
        prototype: HTMLMsevcikAmbulanceWlListElement;
        new (): HTMLMsevcikAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "msevcik-ambulance-wl-app": HTMLMsevcikAmbulanceWlAppElement;
        "msevcik-ambulance-wl-editor": HTMLMsevcikAmbulanceWlEditorElement;
        "msevcik-ambulance-wl-list": HTMLMsevcikAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface MsevcikAmbulanceWlApp {
        "ambulance"?: string;
        "apiUri"?: string;
        "basePath"?: string;
    }
    interface MsevcikAmbulanceWlEditor {
        "ambulance"?: string;
        "apiUri"?: string;
        "entryId"?: string;
        "onCanceled"?: (event: MsevcikAmbulanceWlEditorCustomEvent<WaitingListEntry>) => void;
        "onDeleted"?: (event: MsevcikAmbulanceWlEditorCustomEvent<WaitingListEntry>) => void;
        "onWlChange"?: (event: MsevcikAmbulanceWlEditorCustomEvent<WaitingListEntry>) => void;
    }
    interface MsevcikAmbulanceWlList {
        "ambulance"?: string;
        "apiUri"?: string;
        "onWlEntrySelected"?: (event: MsevcikAmbulanceWlListCustomEvent<string>) => void;
        "selectedEntryId"?: string;
    }
    interface IntrinsicElements {
        "msevcik-ambulance-wl-app": MsevcikAmbulanceWlApp;
        "msevcik-ambulance-wl-editor": MsevcikAmbulanceWlEditor;
        "msevcik-ambulance-wl-list": MsevcikAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "msevcik-ambulance-wl-app": LocalJSX.MsevcikAmbulanceWlApp & JSXBase.HTMLAttributes<HTMLMsevcikAmbulanceWlAppElement>;
            "msevcik-ambulance-wl-editor": LocalJSX.MsevcikAmbulanceWlEditor & JSXBase.HTMLAttributes<HTMLMsevcikAmbulanceWlEditorElement>;
            "msevcik-ambulance-wl-list": LocalJSX.MsevcikAmbulanceWlList & JSXBase.HTMLAttributes<HTMLMsevcikAmbulanceWlListElement>;
        }
    }
}
