name: Build and Test

on:
  push:
    branches:
      - main

  pull_request:
    branches: ["main"]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Run unit tests
      run: npm test

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          msevcik/microfrontends-webcomponent-webui-sample:1.0.0-${{ github.run_number }}
          msevcik/microfrontends-webcomponent-webui-sample:latest
          msevcik/microfrontends-webcomponent-webui-sample:dev-latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
